import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from app.core.config import get_settings
from app.models.schemas import FullReport
import logging

settings = get_settings()

class NotificationService:
    def send_report(self, report: FullReport) -> bool:
        if not settings.EMAIL_ADDRESS or not settings.EMAIL_PASSWORD:
            logging.warning("Email credentials not set. Skipping email.")
            return False

        try:
            msg = MIMEMultipart()
            msg['From'] = settings.EMAIL_ADDRESS
            msg['To'] = settings.RECIPIENT_EMAIL
            msg['Subject'] = f"Daily Stock Intel - {report.date}"

            # Simple HTML Template (Can be enhanced with templating engine)
            html_body = f"""
            <html>
                <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
                    <h2 style="color: #2c3e50;">Daily AI Market Intelligence</h2>
                    <p><strong>Date:</strong> {report.date}</p>
                    
                    <hr>
                    
                    <h3>AI Analysis</h3>
                    <div>{self._markdown_to_html(report.analysis.raw_markdown)}</div>
                    
                    <hr>
                    
                    <h3>Market Snapshot</h3>
                    <h4>Top Gainers</h4>
                    <ul>
                        {''.join([f"<li><strong>{s.ticker}</strong>: {s.change_pct}% (${s.price})</li>" for s in report.market_data.gainers])}
                    </ul>
                    
                    <h4>Sector Performance</h4>
                    <ul>
                        {''.join([f"<li><strong>{k}</strong>: {v}%</li>" for k,v in report.market_data.sector_performance.items()])}
                    </ul>

                    <p style="font-size: 0.8em; color: #999;">Generated by Daily AI Stock Intel System</p>
                </body>
            </html>
            """
            
            msg.attach(MIMEText(html_body, 'html'))
            
            # Connect via SSL
            server = smtplib.SMTP_SSL(settings.EMAIL_HOST, settings.EMAIL_PORT)
            server.login(settings.EMAIL_ADDRESS, settings.EMAIL_PASSWORD)
            server.sendmail(settings.EMAIL_ADDRESS, settings.RECIPIENT_EMAIL.split(','), msg.as_string())
            server.quit()
            
            print(f"Report sent to {settings.RECIPIENT_EMAIL}")
            return True
            
        except Exception as e:
            logging.error(f"Failed to send email: {e}")
            return False
        
    def send_telegram(self, message: str) -> bool:
        """Send message to default/admin Telegram chat"""
        if not settings.TELEGRAM_BOT_TOKEN or not settings.TELEGRAM_CHAT_ID:
            logging.warning("Telegram credentials not set. Skipping notification.")
            return False

        try:
            import requests
            url = f"https://api.telegram.org/bot{settings.TELEGRAM_BOT_TOKEN}/sendMessage"
            payload = {
                "chat_id": settings.TELEGRAM_CHAT_ID,
                "text": message,
                "parse_mode": "Markdown"
            }
            response = requests.post(url, json=payload, timeout=10)
            return response.status_code == 200
        except Exception as e:
            logging.error(f"Failed to send Telegram message: {e}")
            return False
    
    def send_telegram_to_chat(self, chat_id: str, message: str) -> bool:
        """Send message to a specific Telegram chat_id"""
        if not settings.TELEGRAM_BOT_TOKEN:
            logging.warning("Telegram bot token not set. Skipping notification.")
            return False
        
        if not chat_id:
            logging.warning("No chat_id provided. Skipping notification.")
            return False

        try:
            import requests
            url = f"https://api.telegram.org/bot{settings.TELEGRAM_BOT_TOKEN}/sendMessage"
            payload = {
                "chat_id": chat_id,
                "text": message,
                "parse_mode": "Markdown"
            }
            response = requests.post(url, json=payload, timeout=10)
            return response.status_code == 200
        except Exception as e:
            logging.error(f"Failed to send Telegram message to {chat_id}: {e}")
            return False
    
    async def send_telegram_to_user(self, user_id: str, message: str) -> bool:
        """Send Telegram message to a specific user by their user_id"""
        try:
            from app.services.auth_service import auth_service
            
            # Get user's telegram chat_id from preferences
            prefs = await auth_service.get_user_preferences(user_id)
            if not prefs:
                logging.warning(f"No preferences found for user {user_id}")
                return False
            
            chat_id = prefs.get("telegram_chat_id")
            if not chat_id:
                logging.warning(f"User {user_id} has no telegram_chat_id configured")
                return False
            
            if not prefs.get("telegram_enabled", False):
                logging.info(f"Telegram notifications disabled for user {user_id}")
                return False
            
            return self.send_telegram_to_chat(chat_id, message)
        except Exception as e:
            logging.error(f"Failed to send Telegram to user {user_id}: {e}")
            return False

    def _markdown_to_html(self, text: str) -> str:
        # Very basic markdown to html for specific elements used by LLM
        # In prod, use `markdown` library
        html = text.replace('\n', '<br>')
        html = html.replace('**', '<strong>')
        html = html.replace('## ', '<h3>').replace('### ', '<h4>')
        return html
