"""
Signal Tracking Service

Tracks and stores trading signals generated by the AI.
Allows reviewing historical signals and their outcomes.
Includes performance tracking and Telegram notifications.
"""
import json
import os
import requests
from datetime import datetime, timedelta
from typing import List, Dict, Optional
from pydantic import BaseModel
import logging
from dotenv import load_dotenv

# Load .env file explicitly
load_dotenv()

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Telegram Bot Token (optional)
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID', '')

# Log Telegram status
if TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID:
    logger.info("✅ Telegram bot configured for signal alerts")
else:
    logger.info("ℹ️ Telegram bot not configured - alerts disabled")


class TradingSignal(BaseModel):
    """A trading signal record"""
    id: str
    symbol: str
    pair_name: str
    category: str  # forex, stock
    signal: str  # Strong Buy, Buy, Hold, Sell, Strong Sell
    signal_strength: int  # 1-5
    price_at_signal: float
    current_price: Optional[float] = None
    target_price: Optional[float] = None  # Take profit target
    stop_loss: Optional[float] = None
    rsi: Optional[float] = None
    macd_trend: Optional[str] = None
    analysis: Optional[str] = None
    timestamp: str
    outcome: Optional[str] = None  # Win, Loss, Pending, Breakeven
    pnl_pct: Optional[float] = None  # Profit/Loss percentage
    closed_at: Optional[str] = None  # When the signal was closed


class SignalPerformance(BaseModel):
    """Performance statistics for signals"""
    total_signals: int = 0
    wins: int = 0
    losses: int = 0
    breakeven: int = 0
    pending: int = 0
    win_rate: Optional[float] = None  # Percentage
    avg_profit_pct: Optional[float] = None  # Average winning trade profit
    avg_loss_pct: Optional[float] = None  # Average losing trade loss
    total_pnl_pct: float = 0.0  # Total cumulative P&L
    best_trade_pct: Optional[float] = None
    worst_trade_pct: Optional[float] = None
    current_streak: int = 0  # Positive = wins, Negative = losses
    max_win_streak: int = 0
    max_loss_streak: int = 0
    last_7_days_win_rate: Optional[float] = None
    last_30_days_win_rate: Optional[float] = None


class SignalHistory(BaseModel):
    """Collection of signals with statistics"""
    signals: List[TradingSignal]
    total_signals: int
    buy_signals: int
    sell_signals: int
    win_rate: Optional[float] = None
    performance: Optional[SignalPerformance] = None
    last_updated: str


class SignalTrackingService:
    def __init__(self):
        # Store signals in a JSON file for persistence
        self.signals_file = "data/signals_history.json"
        self.signals: List[Dict] = []
        self._load_signals()
    
    def _load_signals(self):
        """Load signals from file"""
        try:
            if os.path.exists(self.signals_file):
                with open(self.signals_file, 'r') as f:
                    self.signals = json.load(f)
                logger.info(f"📋 Loaded {len(self.signals)} historical signals")
        except Exception as e:
            logger.warning(f"Could not load signals: {e}")
            self.signals = []
    
    def _save_signals(self):
        """Save signals to file"""
        try:
            os.makedirs(os.path.dirname(self.signals_file), exist_ok=True)
            with open(self.signals_file, 'w') as f:
                json.dump(self.signals, f, indent=2)
        except Exception as e:
            logger.error(f"Could not save signals: {e}")
    
    def record_signal(self, 
                     symbol: str,
                     pair_name: str,
                     category: str,
                     signal: str,
                     signal_strength: int,
                     price: float,
                     rsi: float = None,
                     macd_trend: str = None,
                     analysis: str = None) -> TradingSignal:
        """
        Record a new trading signal.
        """
        signal_id = f"{symbol.replace('/', '')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
        
        new_signal = {
            "id": signal_id,
            "symbol": symbol,
            "pair_name": pair_name,
            "category": category,
            "signal": signal,
            "signal_strength": signal_strength,
            "price_at_signal": price,
            "current_price": price,
            "rsi": rsi,
            "macd_trend": macd_trend,
            "analysis": analysis,
            "timestamp": datetime.now().isoformat(),
            "outcome": "Pending",
            "pnl_pct": 0.0
        }
        
        # Avoid duplicate signals within 1 hour
        recent_cutoff = (datetime.now() - timedelta(hours=1)).isoformat()
        duplicate = any(
            s['symbol'] == symbol and 
            s['signal'] == signal and 
            s['timestamp'] > recent_cutoff 
            for s in self.signals
        )
        
        if not duplicate:
            self.signals.append(new_signal)
            self._save_signals()
            logger.info(f"📊 Recorded signal: {signal} for {symbol} at {price}")
        
        return TradingSignal(**new_signal)
    
    def update_signal_outcome(self, signal_id: str, current_price: float):
        """
        Update a signal's outcome based on current price.
        """
        for signal in self.signals:
            if signal['id'] == signal_id:
                entry_price = signal['price_at_signal']
                signal['current_price'] = current_price
                
                # Calculate P&L percentage
                if signal['signal'] in ['Strong Buy', 'Buy']:
                    # Long position - profit if price went up
                    pnl = ((current_price - entry_price) / entry_price) * 100
                else:
                    # Short position - profit if price went down
                    pnl = ((entry_price - current_price) / entry_price) * 100
                
                signal['pnl_pct'] = round(pnl, 2)
                
                # Determine outcome using realistic SL/TP levels
                # For forex: 2% SL, 3% TP (1.5:1 RR)
                # Strong signals get more room: 2.5% SL, 4% TP
                is_strong = signal['signal_strength'] >= 4 or signal['signal_strength'] <= 2
                
                sl_pct = 2.5 if is_strong else 2.0
                tp_pct = 4.0 if is_strong else 3.0
                
                if pnl >= tp_pct:
                    signal['outcome'] = 'Win'
                    signal['closed_at'] = datetime.now().isoformat()
                elif pnl <= -sl_pct:
                    signal['outcome'] = 'Loss'
                    signal['closed_at'] = datetime.now().isoformat()
                else:
                    # Still pending - just update current P&L
                    signal['outcome'] = 'Pending'
                
                self._save_signals()
                break
    
    def update_pending_signals(self, current_prices: Dict[str, float]):
        """
        Update all pending signals with current market prices.
        Called whenever market data is fetched.
        
        Args:
            current_prices: Dict mapping symbol (e.g., 'EUR/USD') to current price
        """
        pending_count = 0
        updated_count = 0
        
        for signal in self.signals:
            if signal.get('outcome') in ['Pending', None]:
                pending_count += 1
                symbol = signal['symbol']
                
                if symbol in current_prices:
                    current_price = current_prices[symbol]
                    old_outcome = signal.get('outcome')
                    
                    self.update_signal_outcome(signal['id'], current_price)
                    
                    new_outcome = signal.get('outcome')
                    if new_outcome != 'Pending':
                        updated_count += 1
                        logger.info(f"📊 Signal {symbol} updated: {old_outcome} → {new_outcome} ({signal.get('pnl_pct')}%)")
        
        if updated_count > 0:
            logger.info(f"✅ Updated {updated_count}/{pending_count} pending signals")
        
        return updated_count

    def get_signal_history(self, 
                          category: str = None,
                          limit: int = 50) -> SignalHistory:
        """
        Get historical signals with statistics and performance metrics.
        """
        # Filter by category if specified
        filtered = self.signals
        if category:
            filtered = [s for s in self.signals if s.get('category') == category]
        
        # Sort by timestamp descending
        sorted_signals = sorted(filtered, key=lambda x: x['timestamp'], reverse=True)
        
        # Take only the latest N signals
        recent = sorted_signals[:limit]
        
        # Calculate statistics
        buy_signals = sum(1 for s in recent if s['signal'] in ['Strong Buy', 'Buy'])
        sell_signals = sum(1 for s in recent if s['signal'] in ['Strong Sell', 'Sell'])
        
        # Calculate win rate
        resolved = [s for s in recent if s.get('outcome') in ['Win', 'Loss']]
        wins = sum(1 for s in resolved if s['outcome'] == 'Win')
        win_rate = (wins / len(resolved) * 100) if resolved else None
        
        # Get performance stats
        performance = self.get_performance()
        
        return SignalHistory(
            signals=[TradingSignal(**s) for s in recent],
            total_signals=len(recent),
            buy_signals=buy_signals,
            sell_signals=sell_signals,
            win_rate=round(win_rate, 1) if win_rate else None,
            performance=performance,
            last_updated=datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        )
    
    def get_performance(self) -> SignalPerformance:
        """
        Calculate comprehensive performance statistics.
        """
        if not self.signals:
            return SignalPerformance()
        
        # Count outcomes
        wins = [s for s in self.signals if s.get('outcome') == 'Win']
        losses = [s for s in self.signals if s.get('outcome') == 'Loss']
        breakeven = [s for s in self.signals if s.get('outcome') == 'Breakeven']
        pending = [s for s in self.signals if s.get('outcome') == 'Pending' or not s.get('outcome')]
        
        total_resolved = len(wins) + len(losses)
        win_rate = (len(wins) / total_resolved * 100) if total_resolved > 0 else None
        
        # Calculate average P&L
        win_pnls = [s.get('pnl_pct', 0) for s in wins if s.get('pnl_pct')]
        loss_pnls = [s.get('pnl_pct', 0) for s in losses if s.get('pnl_pct')]
        all_pnls = [s.get('pnl_pct', 0) for s in self.signals if s.get('pnl_pct')]
        
        avg_profit = sum(win_pnls) / len(win_pnls) if win_pnls else None
        avg_loss = sum(loss_pnls) / len(loss_pnls) if loss_pnls else None
        total_pnl = sum(all_pnls)
        
        best_trade = max(all_pnls) if all_pnls else None
        worst_trade = min(all_pnls) if all_pnls else None
        
        # Calculate streaks
        sorted_signals = sorted(
            [s for s in self.signals if s.get('outcome') in ['Win', 'Loss']], 
            key=lambda x: x['timestamp']
        )
        
        current_streak = 0
        max_win_streak = 0
        max_loss_streak = 0
        temp_streak = 0
        last_outcome = None
        
        for s in sorted_signals:
            outcome = s.get('outcome')
            if outcome == last_outcome:
                temp_streak += 1 if outcome == 'Win' else -1
            else:
                temp_streak = 1 if outcome == 'Win' else -1
            
            last_outcome = outcome
            current_streak = temp_streak
            
            if temp_streak > max_win_streak:
                max_win_streak = temp_streak
            if temp_streak < max_loss_streak:
                max_loss_streak = temp_streak
        
        # Calculate time-based win rates
        now = datetime.now()
        last_7_days = now - timedelta(days=7)
        last_30_days = now - timedelta(days=30)
        
        recent_7 = [s for s in self.signals if datetime.fromisoformat(s['timestamp']) > last_7_days]
        recent_30 = [s for s in self.signals if datetime.fromisoformat(s['timestamp']) > last_30_days]
        
        resolved_7 = [s for s in recent_7 if s.get('outcome') in ['Win', 'Loss']]
        resolved_30 = [s for s in recent_30 if s.get('outcome') in ['Win', 'Loss']]
        
        wins_7 = sum(1 for s in resolved_7 if s['outcome'] == 'Win')
        wins_30 = sum(1 for s in resolved_30 if s['outcome'] == 'Win')
        
        last_7_win_rate = (wins_7 / len(resolved_7) * 100) if resolved_7 else None
        last_30_win_rate = (wins_30 / len(resolved_30) * 100) if resolved_30 else None
        
        return SignalPerformance(
            total_signals=len(self.signals),
            wins=len(wins),
            losses=len(losses),
            breakeven=len(breakeven),
            pending=len(pending),
            win_rate=round(win_rate, 1) if win_rate else None,
            avg_profit_pct=round(avg_profit, 2) if avg_profit else None,
            avg_loss_pct=round(avg_loss, 2) if avg_loss else None,
            total_pnl_pct=round(total_pnl, 2),
            best_trade_pct=round(best_trade, 2) if best_trade else None,
            worst_trade_pct=round(worst_trade, 2) if worst_trade else None,
            current_streak=current_streak,
            max_win_streak=max_win_streak,
            max_loss_streak=abs(max_loss_streak),
            last_7_days_win_rate=round(last_7_win_rate, 1) if last_7_win_rate else None,
            last_30_days_win_rate=round(last_30_win_rate, 1) if last_30_win_rate else None
        )
    
    def send_telegram_alert(self, signal: Dict) -> bool:
        """
        Send a Telegram notification for a new signal.
        """
        if not TELEGRAM_BOT_TOKEN or not TELEGRAM_CHAT_ID:
            return False
        
        try:
            emoji = "🟢" if "Buy" in signal['signal'] else "🔴"
            
            message = f"""
{emoji} *NEW SIGNAL: {signal['signal'].upper()}*

📊 *{signal['symbol']}* ({signal['pair_name']})

💰 Entry Price: `{signal['price_at_signal']}`
🎯 Target: `{signal.get('target_price', 'Calculate in app')}`
🛑 Stop Loss: `{signal.get('stop_loss', 'Calculate in app')}`

📈 RSI: {signal.get('rsi', 'N/A')}
📉 MACD: {signal.get('macd_trend', 'N/A')}

⏰ {datetime.now().strftime('%Y-%m-%d %H:%M')}

_Click for full analysis in StockPulse AI_
            """
            
            url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
            payload = {
                "chat_id": TELEGRAM_CHAT_ID,
                "text": message,
                "parse_mode": "Markdown"
            }
            
            response = requests.post(url, json=payload, timeout=10)
            
            if response.status_code == 200:
                logger.info(f"📱 Telegram alert sent for {signal['symbol']}")
                return True
            else:
                logger.warning(f"⚠️ Telegram API error: {response.status_code}")
                return False
                
        except Exception as e:
            logger.warning(f"⚠️ Telegram send failed: {e}")
            return False
    
    def record_forex_signals(self, forex_pairs: List):
        """
        Record signals from forex pairs data.
        Called after fetching forex data.
        """
        for pair in forex_pairs:
            if pair.technicals and pair.technicals.signal:
                # Record Buy and Sell signals (strength 1-2 or 4-5)
                if pair.technicals.signal_strength >= 4 or pair.technicals.signal_strength <= 2:
                    new_signal = self.record_signal(
                        symbol=pair.symbol,
                        pair_name=pair.name,
                        category="forex",
                        signal=pair.technicals.signal,
                        signal_strength=pair.technicals.signal_strength,
                        price=pair.price,
                        rsi=pair.technicals.rsi,
                        macd_trend=pair.technicals.macd_trend,
                        analysis=pair.analysis
                    )
                    
                    # Send Telegram alert for ALL buy and sell signals
                    if pair.technicals.signal_strength >= 4 or pair.technicals.signal_strength <= 2:
                        self.send_telegram_alert({
                            'symbol': pair.symbol,
                            'pair_name': pair.name,
                            'signal': pair.technicals.signal,
                            'price_at_signal': pair.price,
                            'rsi': pair.technicals.rsi,
                            'macd_trend': pair.technicals.macd_trend
                        })


# Singleton instance
signal_service = SignalTrackingService()

